server:
  port: 8081
spring:
  application:
    name: petclinic-customer-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
