version: '3.8'

services:
  first-db:
    container_name: "first-db"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: first_db
    ports:
      - "3307:3306"
    volumes:
      - "./scripts/init1.sql:/docker-entrypoint-initdb.d/1.sql"

  second-db:
    container_name: "second-db"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: second_db
    ports:
      - "3308:3306"
    volumes:
      - "./scripts/init2.sql:/docker-entrypoint-initdb.d/1.sql"