create table PRODUCT_AMOUNT (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_id INT,
  amount INT
);

INSERT INTO PRODUCT_AMOUNT VALUES (1, 1, 10);
INSERT INTO PRODUCT_AMOUNT VALUES (2, 2, 100);
INSERT INTO PRODUCT_AMOUNT VALUES (3, 3, 3);