spring:
  application:
    name: petclinic-discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

# Avoid some debugging logs at startup
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO
eureka:
  dashboard:
    path: /eurekawebui
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888


#
